[build]
  command = "npx prisma generate && DATABASE_URL=\"postgresql://postgres:ElaSovereign2024!@db.yoqgvuwtseoctwwjlapy.supabase.co:5432/postgres?sslmode=require\" npx prisma db push --accept-data-loss && DATABASE_URL=\"postgresql://postgres:ElaSovereign2024!@db.yoqgvuwtseoctwwjlapy.supabase.co:5432/postgres?sslmode=require\" node scripts/netlify-seed.js && npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Forwarding API Routes for Netlify Functions (Optional if using raw Next.js, but required for custom Netlify Scheduled Functions built outside of Next boundary)
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
