[build]
  command = "DATABASE_URL='postgresql://postgres.yoqgvuwtseoctwwjlapy:ElaSovereign2026Gen@aws-1-eu-west-1.pooler.supabase.com:6543/postgres?sslmode=require&pgbouncer=true' NEXTAUTH_SECRET='ela-sovereign-genesis-nextauth-secret-2026-fortress' NEXTAUTH_URL='https://storied-longma-396754.netlify.app' NEXT_PUBLIC_APP_URL='https://storied-longma-396754.netlify.app' CI=false NODE_OPTIONS='--max-old-space-size=4096' npx prisma generate && next build"
  publish = ".next"



# Forwarding API Routes for Netlify Functions (Optional if using raw Next.js, but required for custom Netlify Scheduled Functions built outside of Next boundary)
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
