[build]
  command = "bash scripts/build-prod.sh"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Forwarding API Routes for Netlify Functions (Optional if using raw Next.js, but required for custom Netlify Scheduled Functions built outside of Next boundary)
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
